# Generated by Django 6.0.4 on 2026-05-15 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id_entrenador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'entrenador',
            },
        ),
        migrations.CreateModel(
            name='EstadoPista',
            fields=[
                ('id_estado_pista', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_pista',
            },
        ),
        migrations.CreateModel(
            name='Hipodromo',
            fields=[
                ('id_hipodromo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'hipodromo',
            },
        ),
        migrations.CreateModel(
            name='Jinete',
            fields=[
                ('id_jinete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jinete',
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id_pista', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pista',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('equipamiento', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'propietario',
            },
        ),
        migrations.CreateModel(
            name='TipoApuesta',
            fields=[
                ('id_tipo_apuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipos_apuesta',
            },
        ),
        migrations.CreateModel(
            name='Caballo',
            fields=[
                ('id_caballo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('entrenador', models.ForeignKey(db_column='id_entrenador', on_delete=django.db.models.deletion.PROTECT, to='datos.entrenador')),
                ('propietario', models.ForeignKey(db_column='id_propietario', on_delete=django.db.models.deletion.PROTECT, to='datos.propietario')),
            ],
            options={
                'db_table': 'caballo',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('enlace', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('distancia', models.IntegerField()),
                ('orden', models.IntegerField()),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('id_estado_pista', models.ForeignKey(db_column='id_estado_pista', on_delete=django.db.models.deletion.RESTRICT, to='datos.estadopista')),
                ('id_hipodromo', models.ForeignKey(db_column='id_hipodromo', on_delete=django.db.models.deletion.RESTRICT, to='datos.hipodromo')),
                ('id_pista', models.ForeignKey(db_column='id_pista', on_delete=django.db.models.deletion.RESTRICT, to='datos.pista')),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('numero_salida', models.IntegerField()),
                ('retirado', models.BooleanField(default=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caballo', models.ForeignKey(db_column='id_caballo', on_delete=django.db.models.deletion.CASCADE, to='datos.caballo')),
                ('carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.CASCADE, to='datos.carrera')),
                ('jinete', models.ForeignKey(db_column='id_jinete', on_delete=django.db.models.deletion.CASCADE, to='datos.jinete')),
            ],
            options={
                'db_table': 'participante',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.IntegerField()),
                ('duracion', models.TimeField()),
                ('distancia', models.CharField(max_length=20)),
                ('participante', models.OneToOneField(db_column='id_participante', on_delete=django.db.models.deletion.CASCADE, to='datos.participante')),
            ],
            options={
                'db_table': 'resultado',
            },
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id_apuesta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participante', models.ForeignKey(db_column='id_participante', on_delete=django.db.models.deletion.CASCADE, to='datos.participante')),
                ('tipo_apuesta', models.ForeignKey(db_column='id_tipo_apuesta', on_delete=django.db.models.deletion.PROTECT, to='datos.tipoapuesta')),
            ],
            options={
                'db_table': 'apuesta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nac', models.DateField()),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('jinete', 'carrera'), name='unique_jinete_carrera'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('caballo', 'carrera'), name='unique_caballo_carrera'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('numero_salida', 'carrera'), name='unique_salida_carrera'),
        ),
    ]
