# Generated by Django 6.0.4 on 2026-05-20 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participante',
            name='caballo',
            field=models.ForeignKey(db_column='id_caballo', on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='datos.caballo'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='carrera',
            field=models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='datos.carrera'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='jinete',
            field=models.ForeignKey(db_column='id_jinete', on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='datos.jinete'),
        ),
    ]
